In [1]:
!pip install numpy

In [1]:
import numpy as np

# Create

In [2]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [3]:
data

array([[[0.31930747, 0.80726267, 0.6985485 , 0.06175441],
        [0.03680681, 0.6332295 , 0.40925366, 0.5968203 ],
        [0.25204361, 0.26581243, 0.54782596, 0.15903813]],

       [[0.6112234 , 0.989888  , 0.97831428, 0.96623196],
        [0.67424119, 0.15557941, 0.35856231, 0.27928041],
        [0.78681073, 0.07402485, 0.16831363, 0.09436937]]])

In [4]:
# all number zeros
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [5]:
#replace all number into 7
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [6]:
# replace all number into 1
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## Convert list into numpy array

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
type(arr)

numpy.ndarray

# Read

In [13]:
## Attributes
shape = data.shape
size = data.size
types = data.dtype

In [14]:
shape

(2, 3, 4)

In [16]:
size

24

In [15]:
types

dtype('float64')

In [22]:
## Slicing
arr = data[0] #taking first array
slicer = data[0][0:2] #taking first 2 array in first array
reverse = data[-1] #taking last array
singleval = data[0][0][0] #taking single value in first array

In [18]:
arr

array([[0.31930747, 0.80726267, 0.6985485 , 0.06175441],
       [0.03680681, 0.6332295 , 0.40925366, 0.5968203 ],
       [0.25204361, 0.26581243, 0.54782596, 0.15903813]])

In [23]:
slicer

array([[0.31930747, 0.80726267, 0.6985485 , 0.06175441],
       [0.03680681, 0.6332295 , 0.40925366, 0.5968203 ]])

In [24]:
reverse

array([[0.6112234 , 0.989888  , 0.97831428, 0.96623196],
       [0.67424119, 0.15557941, 0.35856231, 0.27928041],
       [0.78681073, 0.07402485, 0.16831363, 0.09436937]])

In [25]:
singleval

0.319307474752606

# Update

In [26]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [29]:
print(list1,'\n\n', list2)

[0.24765723 0.74574575 0.5717357  0.05921543 0.30512791 0.39024965
 0.43089506 0.54938333 0.03226597 0.10209374] 

 [0.11696263 0.37253822 0.49849097 0.66878538 0.55979153 0.54810469
 0.31036595 0.4892648  0.96280588 0.26302042]


## Basic Math

In [30]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [32]:
mult

array([0.02896664, 0.2778188 , 0.28500508, 0.03960241, 0.17080802,
       0.21389766, 0.13373515, 0.26879393, 0.03106586, 0.02685274])

# Statistical Function

In [34]:
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [40]:
exp

array([ 7.3890561 , 20.08553692])

## Update data in array

In [41]:
data[0][0][0] = 700

In [42]:
data

array([[[7.00000000e+02, 8.07262674e-01, 6.98548496e-01, 6.17544149e-02],
        [3.68068142e-02, 6.33229503e-01, 4.09253665e-01, 5.96820295e-01],
        [2.52043612e-01, 2.65812432e-01, 5.47825957e-01, 1.59038127e-01]],

       [[6.11223400e-01, 9.89888000e-01, 9.78314284e-01, 9.66231960e-01],
        [6.74241192e-01, 1.55579412e-01, 3.58562311e-01, 2.79280413e-01],
        [7.86810727e-01, 7.40248503e-02, 1.68313633e-01, 9.43693673e-02]]])

In [44]:
data.sort() ;data

array([[[6.17544149e-02, 6.98548496e-01, 8.07262674e-01, 7.00000000e+02],
        [3.68068142e-02, 4.09253665e-01, 5.96820295e-01, 6.33229503e-01],
        [1.59038127e-01, 2.52043612e-01, 2.65812432e-01, 5.47825957e-01]],

       [[6.11223400e-01, 9.66231960e-01, 9.78314284e-01, 9.89888000e-01],
        [1.55579412e-01, 2.79280413e-01, 3.58562311e-01, 6.74241192e-01],
        [7.40248503e-02, 9.43693673e-02, 1.68313633e-01, 7.86810727e-01]]])

## Reshaping array

In [47]:
data.shape

(2, 3, 4)

In [49]:
# reshape into 2 by 2 array and doesn't care last value
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

## Adding new value (append/insert)

In [53]:
zeroes = np.zeros((8)) ;print(zeroes)
zeroes = np.append(zeroes, [3,4]) ;print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [54]:
# insert '1' in position 2
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# Delete

In [55]:
data

array([[[6.17544149e-02, 6.98548496e-01, 8.07262674e-01, 7.00000000e+02,
         3.68068142e-02, 4.09253665e-01],
        [5.96820295e-01, 6.33229503e-01, 1.59038127e-01, 2.52043612e-01,
         2.65812432e-01, 5.47825957e-01]],

       [[6.11223400e-01, 9.66231960e-01, 9.78314284e-01, 9.89888000e-01,
         1.55579412e-01, 2.79280413e-01],
        [3.58562311e-01, 6.74241192e-01, 7.40248503e-02, 9.43693673e-02,
         1.68313633e-01, 7.86810727e-01]]])

In [56]:
# delete first array in each array 
np.delete(data, 0, axis=1)

array([[[0.5968203 , 0.6332295 , 0.15903813, 0.25204361, 0.26581243,
         0.54782596]],

       [[0.35856231, 0.67424119, 0.07402485, 0.09436937, 0.16831363,
         0.78681073]]])

## Save numpy array

In [57]:
np.save("test save", data)

In [58]:
test_read = np.load('test save.npy')

In [59]:
test_read

array([[[6.17544149e-02, 6.98548496e-01, 8.07262674e-01, 7.00000000e+02,
         3.68068142e-02, 4.09253665e-01],
        [5.96820295e-01, 6.33229503e-01, 1.59038127e-01, 2.52043612e-01,
         2.65812432e-01, 5.47825957e-01]],

       [[6.11223400e-01, 9.66231960e-01, 9.78314284e-01, 9.89888000e-01,
         1.55579412e-01, 2.79280413e-01],
        [3.58562311e-01, 6.74241192e-01, 7.40248503e-02, 9.43693673e-02,
         1.68313633e-01, 7.86810727e-01]]])